# Generated by Django 4.2.7 on 2023-12-27 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
