# Generated by Django 4.2.7 on 2024-01-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
