# Generated by Django 4.2.7 on 2024-01-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='base_amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='discount_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tax',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='credits',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='discount_applied',
            field=models.CharField(max_length=255),
        ),
    ]
