# Generated by Django 4.2.7 on 2024-01-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_rename_buyer_transaction_buyer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='base_amount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='discount_applied',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='credits',
            field=models.IntegerField(default=10),
        ),
    ]
