# Generated by Django 4.2.7 on 2024-01-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_rename_base_amount_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='credits',
            field=models.IntegerField(),
        ),
    ]
